apiVersion: v1
name: flagger
version: 0.27.0
appVersion: 1.0.0-rc.4
kubeVersion: ">=1.11.0-0"
engine: gotpl
description: Flagger is a progressive delivery operator for Kubernetes
home: https://flagger.app
icon: https://raw.githubusercontent.com/weaveworks/flagger/master/docs/logo/weaveworks.png
sources:
  - https://github.com/weaveworks/flagger
maintainers:
  - name: stefanprodan
    url: https://github.com/stefanprodan
    email: stefanprodan@users.noreply.github.com
keywords:
  - flagger
  - istio
  - appmesh
  - linkerd
  - gloo
  - gitops
  - canary
