apiVersion: v1
name: flagger
version: 1.11.0
appVersion: 1.11.0
kubeVersion: ">=1.16.0-0"
engine: gotpl
description: Flagger is a progressive delivery operator for Kubernetes
home: https://flagger.app
icon: https://raw.githubusercontent.com/fluxcd/flagger/main/docs/logo/flagger-icon.png
sources:
  - https://github.com/fluxcd/flagger
maintainers:
  - name: stefanprodan
    url: https://github.com/stefanprodan
    email: stefanprodan@users.noreply.github.com
keywords:
  - flagger
  - istio
  - appmesh
  - linkerd
  - gloo
  - contour
  - nginx
  - traefik
  - gitops
  - canary
