apiVersion: v1
name: loadtester
version: 0.29.0
appVersion: 0.29.0
kubeVersion: ">=1.19.0-0"
engine: gotpl
description: Flagger's load testing services based on rakyll/hey and bojand/ghz that generates traffic during canary analysis when configured as a webhook.
home: https://docs.flagger.app
icon: https://raw.githubusercontent.com/fluxcd/flagger/main/docs/logo/flagger-icon.png
sources:
  - https://github.com/fluxcd/flagger
maintainers:
  - name: stefanprodan
    url: https://github.com/stefanprodan
    email: stefanprodan@users.noreply.github.com
keywords:
  - flagger
  - istio
  - appmesh
  - linkerd
  - gloo
  - osm
  - smi
  - gitops
  - load testing
