apiVersion: v1
name: loadtester
version: 0.7.0
appVersion: 0.7.0
kubeVersion: ">=1.11.0-0"
engine: gotpl
description: Flagger's load testing services based on rakyll/hey and bojand/ghz that generates traffic during canary analysis when configured as a webhook.
home: https://docs.flagger.app
icon: https://raw.githubusercontent.com/weaveworks/flagger/master/docs/logo/flagger-icon.png
sources:
  - https://github.com/weaveworks/flagger
maintainers:
  - name: stefanprodan
    url: https://github.com/stefanprodan
    email: stefanprodan@users.noreply.github.com
keywords:
  - canary
  - istio
  - appmesh
  - gitops
  - load testing
