replicaCount: 1

image:
  repository: weaveworks/flagger-loadtester
  tag: 0.15.0
  pullPolicy: IfNotPresent

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"

logLevel: info
cmd:
  timeout: 1h

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

rbac:
  # rbac.create: `true` if rbac resources should be created
  create: false
  # rbac.scope: `cluster` to create cluster-scope rbac resources (ClusterRole/ClusterRoleBinding)
  # otherwise, namespace-scope rbac resources will be created (Role/RoleBinding)
  scope:
  # rbac.rules: array of rules to apply to the role. example:
  # rules:
  # - apiGroups: [""]
  #   resources: ["pods"]
  #   verbs: ["list", "get"]
  rules: []

# name of an existing service account to use - if not creating rbac resources
serviceAccountName: ""

# App Mesh virtual node settings
meshName: ""
#backends:
#  - app1.namespace
#  - app2.namespace
