replicaCount: 1

image:
  repository: ghcr.io/fluxcd/flagger-loadtester
  tag: 0.29.0
  pullPolicy: IfNotPresent
  pullSecret:

podLabels: {}

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"

podPriorityClassName: ""

logLevel: info
cmd:
  timeout: 1h
  namespaceRegexp: ""

nameOverride: ""
fullnameOverride: ""

env: []

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 10m
    memory: 64Mi

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

rbac:
  # rbac.create: `true` if rbac resources should be created
  create: false
  # rbac.scope: `cluster` to create cluster-scope rbac resources (ClusterRole/ClusterRoleBinding)
  # otherwise, namespace-scope rbac resources will be created (Role/RoleBinding)
  scope:
  # rbac.rules: array of rules to apply to the role. example:
  # rules:
  # - apiGroups: [""]
  #   resources: ["pods"]
  #   verbs: ["list", "get"]
  rules: []

# name of an existing service account to use - if not creating rbac resources
serviceAccountName: ""

# App Mesh virtual node settings (to be used for AppMesh v1beta1)
meshName: ""
#backends:
#  - app1.namespace
#  - app2.namespace

# App Mesh virtual node settings (to be used for AppMesh v1beta2)
appmesh:
  enabled: false
  backends:
  - podinfo
  - podinfo-canary

#Istio virtual service and gatway settings. TLS secrets should be in namespace before enbaled it. ( secret format loadtester.fullname )
istio:
  enabled: false
  host: flagger-loadtester.flagger
  gateway:
    enabled: false
  tls:
    enabled: false
    httpsRedirect: false

# when enabled, it will add a security context for the loadtester pod
securityContext:
  enabled: false
  context:
    readOnlyRootFilesystem: true
    runAsUser: 100
    runAsGroup: 101

podDisruptionBudget:
  enabled: false
  minAvailable: 1
