apiVersion: v1
version: 5.0.0
appVersion: 5.0.0
name: podinfo
engine: gotpl
description: Flagger canary deployment demo application
home: https://docs.flagger.app
icon: https://raw.githubusercontent.com/fluxcd/flagger/main/docs/logo/flagger-icon.png
sources:
  - https://github.com/stefanprodan/podinfo
maintainers:
  - name: stefanprodan
    url: https://github.com/stefanprodan
    email: stefanprodan@users.noreply.github.com
