# Default values for podinfo.
image:
  repository: stefanprodan/podinfo
  tag: 2.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9898

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 2
  cpu: 80
  memory: 512Mi

canary:
  enabled: true
  # Istio traffic policy tls can be DISABLE or ISTIO_MUTUAL
  istioTLS: DISABLE
  istioIngress:
    enabled: false
    # Istio ingress gateway name
    gateway: public-gateway.istio-system.svc.cluster.local
    # external host name eg. podinfo.example.com
    host:
  analysis:
    # schedule interval (default 60s)
    interval: 15s
    # max number of failed metric checks before rollback
    threshold: 10
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 5
  thresholds:
    # minimum req success rate (non 5xx responses)
    # percentage (0-100)
    successRate: 99
    # maximum req duration P99
    # milliseconds
    latency: 500
  loadtest:
    enabled: false
    # load tester address
    url: http://flagger-loadtester.test/
  helmtest:
    enabled: false
    # helm tester address
    url: http://flagger-helmtester.kube-system/

resources:
  limits:
  requests:
    cpu: 100m
    memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}

nameOverride: ""
fullnameOverride: ""

logLevel: info
backend: #http://backend-podinfo:9898/echo
message: #UI greetings

faults:
  delay: false
  error: false

httpServer:
  timeout: 30s
