apiVersion: v1
name: grafana
version: 1.6.0
appVersion: 7.2.0
description: Grafana dashboards for monitoring Flagger canary deployments
icon: https://raw.githubusercontent.com/fluxcd/flagger/main/docs/logo/flagger-icon.png
home: https://flagger.app
sources:
  - https://github.com/fluxcd/flagger
maintainers:
  - name: stefanprodan
    url: https://github.com/stefanprodan
    email: stefanprodan@users.noreply.github.com
keywords:
  - flagger
  - grafana
  - canary
  - istio
  - appmesh

