apiVersion: v1
name: grafana
version: 1.4.0
appVersion: 6.5.1
description: Grafana dashboards for monitoring Flagger canary deployments
icon: https://raw.githubusercontent.com/weaveworks/flagger/master/docs/logo/weaveworks.png
home: https://flagger.app
sources:
  - https://github.com/weaveworks/flagger
maintainers:
  - name: stefanprodan
    url: https://github.com/stefanprodan
    email: stefanprodan@users.noreply.github.com
keywords:
  - flagger
  - grafana
  - canary
  - istio
  - appmesh

