{{- if .Values.crd.create }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: canaries.flagger.app
spec:
  group: flagger.app
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    plural: canaries
    singular: canary
    kind: Canary
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
          - targetRef
          - service
          - canaryAnalysis
          properties:
            targetRef:
              properties:
                apiVersion:
                  type: string
                kind:
                  type: string
                name:
                  type: string
            service:
              properties:
                port:
                  type: number
            canaryAnalysis:
              properties:
                threshold:
                  type: number
                maxWeight:
                  type: number
                stepWeight:
                  type: number
                metrics:
                  type: array
                  properties:
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        interval:
                          type: string
                          pattern: "^[0-9]+(m)"
                        threshold:
                          type: number
{{- end }}
