{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "flagger.fullname" . }}
  labels:
    helm.sh/chart: {{ template "flagger.chart" . }}
    app.kubernetes.io/name: {{ template "flagger.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - configmaps
      - secrets
      - services
    verbs: ["*"]
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs: ["*"]
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs: ["*"]
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
      - ingresses/status
    verbs: ["*"]
  - apiGroups:
      - flagger.app
    resources:
      - canaries
      - canaries/status
    verbs: ["*"]
  - apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
      - virtualservices/status
      - destinationrules
      - destinationrules/status
    verbs: ["*"]
  - apiGroups:
      - appmesh.k8s.aws
    resources:
      - meshes
      - meshes/status
      - virtualnodes
      - virtualnodes/status
      - virtualservices
      - virtualservices/status
    verbs: ["*"]
  - apiGroups:
      - split.smi-spec.io
    resources:
      - trafficsplits
    verbs: ["*"]
  - apiGroups:
      - gloo.solo.io
    resources:
      - settings
      - upstreams
      - upstreamgroups
      - proxies
      - virtualservices
    verbs: ["*"]
  - apiGroups:
      - gateway.solo.io
    resources:
      - virtualservices
      - gateways
    verbs: ["*"]
  - nonResourceURLs:
      - /version
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "flagger.fullname" . }}
  labels:
    helm.sh/chart: {{ template "flagger.chart" . }}
    app.kubernetes.io/name: {{ template "flagger.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "flagger.fullname" . }}
subjects:
- name: {{ template "flagger.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
{{- end }}
