apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "appmesh-gateway.fullname" . }}
  labels:
{{ include "appmesh-gateway.labels" . | indent 4 }}
data:
  envoy.yaml: |-
    admin:
      access_log_path: {{ .Values.proxy.access_log_path }}
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8081

    dynamic_resources:
      ads_config:
        api_type: GRPC
        grpc_services:
          - envoy_grpc:
              cluster_name: xds
      cds_config:
        ads: {}
      lds_config:
        ads: {}

    static_resources:
      clusters:
        - name: xds
          connect_timeout: 0.50s
          type: static
          http2_protocol_options: {}
          load_assignment:
            cluster_name: xds
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: 18000
