name: e2e

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        provider:
          # service mesh
          - istio
          - linkerd
          - kuma
          # ingress controllers
          - contour
          - nginx
          - traefik
          - gloo
          - skipper
          - kubernetes
          - gatewayapi
          - keda
          - apisix
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Kubernetes
        uses: helm/kind-action@v1.8.0
        if: matrix.provider != 'skipper'
        with:
          version: v0.20.0
          cluster_name: kind
          node_image: kindest/node:v1.27.3@sha256:9dd3392d79af1b084671b05bcf65b21de476256ad1dcc853d9f3b10b4ac52dde
      - name: Setup Kubernetes for skipper
        uses: helm/kind-action@v1.8.0
        if: matrix.provider == 'skipper'
        with:
          version: v0.20.0
          cluster_name: kind
          node_image: kindest/node:v1.24.12@sha256:0bdca26bd7fe65c823640b14253ea7bac4baad9336b332c94850f84d8102f873
      - name: Build container image
        run: |
          docker build -t test/flagger:latest .
          kind load docker-image test/flagger:latest
      - name: Run tests
        run: |
          ./test/${{ matrix['provider'] }}/run.sh
